SilverStripe\Security\MemberAuthenticator\LoginForm:
  required_fields:
    - Email
    - Password

SilverStripe\Security\Security:
  authenticators:
    default: SilverStripe\Security\MemberAuthenticator\Authenticator
    cms: SilverStripe\Security\MemberAuthenticator\CMSAuthenticator

SilverStripe\Security\MemberAuthenticator\CMSSecurity:
  reauth_enabled: true